#
# Set up minion
#
---
- name: Enable kubelet
  service: name=kubelet enabled=yes

- name: Copy join script (fetched in 'join-token' role)
  copy: src=/tmp/join-worker-node.sh dest=/root/join-worker-node.sh owner=root group=root mode=0755

- name: Join join-worker-node
  command: sh /root/join-worker-node.sh