#
# Prepare node (i.e. set up and fix some files)
#
---

- name: Make sure some needed software is installed via package manager
  package: name={{ item }} state=present
  with_items:
  - perl
  - kubelet-{{ KUBERNETES_VERSION }}
  - kubectl-{{ KUBERNETES_VERSION }}
  - kubeadm-{{ KUBERNETES_VERSION }}
  - kubernetes-cni-{{ KUBERNETES_CNI_VERSION }}

- name: Set cgroups driver to 'cgroupfs' 
  command: "perl -pi -e 's/--cgroup-driver=systemd/--cgroup-driver=cgroupfs/g' /etc/systemd/system/kubelet.service.d/10-kubeadm.conf"

- name: Reload systemd units
  # Fixme: 2.3.1.0 wants a 'name' argument here which is of course nonsense
  #systemd: daemon-reload=yes
  command: systemctl daemon-reload

- name: Create setup directory 
  file: path=/root/setup state=directory
  when: "'primary-master' in group_names"
