#
# Playbook to set up a Kubernetes cluster.
#
--- 

- name: Uninstall Cluster
  hosts: nodes
  remote_user: root
  gather_facts: no
  any_errors_fatal: yes
  roles:
  - uninstall
  tags:
  - uninstall-cluster

