#
# Apply settings on the redundant masters.
#
---

- name: Set kube-dns replicas.
  shell: export KUBECONFIG=/etc/kubernetes/admin.conf; kubectl scale --replicas={{ groups['masters'] | length }} -n kube-system deployment/kube-dns

