#
# Get a new join token from the primary master in order to add worker nodes.
#
---
- name: Generate a command line with join token for adding worker nodes
  shell: echo "kubeadm join --token `kubeadm token create` {{ ansible_default_ipv4.address }}:6443 --discovery-token-ca-cert-hash sha256:`openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | openssl rsa -pubin -outform der 2>/dev/null | openssl dgst -sha256 -hex | sed "s/^.* //"`" >/tmp/join-worker-node.sh

- name: Fetch script with generated command line for adding worker nodes
  fetch: src=/tmp/join-worker-node.sh dest=/tmp/ flat=yes
