#
# Initialise primary master
#
---

- name: Generate 'kubeadm' configuration file
  template: src=kubeadm-init.yaml.j2 dest=/root/kubeadm-init.yaml

- name: Run 'kubeadm'
  command: kubeadm init --config=/root/kubeadm-init.yaml

- name: Archive /etc/kubernetes/pki/[cs]a.*
  archive: path=/etc/kubernetes/pki/[cs]a.* dest=/tmp/master-certs.tar.gz

- name: Fetch /tmp/master-certs.tar.gz
  fetch: src=/tmp/master-certs.tar.gz dest=/tmp/ flat=yes

